<?php

namespace Projet\YdaysManagerUserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchStudent(){
    $qb = $this->createQueryBuilder('u');
    $qb->where('u.promotion != :identifier')
       ->setParameter('identifier', 'null');

    return $qb->getQuery()
          ->getResult();
    }
}
