# app/config/security.yml

security:
  encoders:
    Projet\YdaysManagerUserBundle\Entity\User: sha512

  role_hierarchy:
      ROLE_HELPER:          ROLE_USER
      ROLE_PROJECT_MANAGER: ROLE_USER
      ROLE_ADMIN:           [ROLE_HELPER, ROLE_PROJECT_MANAGER]
      ROLE_SUPER_ADMIN:     ROLE_ADMIN

  providers:
    main:
      id: fos_user.user_provider.username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    # On crée un pare-feu uniquement pour le formulaire
    main_login:
        # Cette expression régulière permet de prendre /login (mais pas /login_check !)
        pattern:   ^/login$
        anonymous: true # On autorise alors les anonymes sur ce pare-feu
    main:
      pattern:   ^/
      anonymous: true
      provider: main
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
        # login success redirecting options
        always_use_default_target_path: true
        default_target_path:            /accueil
      logout:
        path:       fos_user_security_logout
        target:     fos_user_security_login
      remember_me:
        secret:     %secret% # %secret% est un paramètre de parameter

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
