<?php

namespace Projet\YdaysManagerBundle\Repository;

/**
 * AnswerCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
