<?php

namespace Projet\YdaysManagerBundle\Repository;

/**
 * DesireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesireRepository extends \Doctrine\ORM\EntityRepository
{
}
