projet_ydays_manager_project:
  path:      /projects
  defaults:
      _controller: ProjetYdaysManagerBundle:Project:lesProjets

projet_ydays_manager_proposer_projet:
  path:      /proposerProjet
  defaults:
      _controller: ProjetYdaysManagerBundle:Project:proposerProjet

projet_ydays_manager_fiche_projet:
   path:     /ficheProjet/{id}
   defaults:
       _controller: ProjetYdaysManagerBundle:Project:ficheProjet
   requirements:
       id: \d+

projet_ydays_manager_liste_etudiant:
    path:     /listeEtudiant
    defaults:
        _controller: ProjetYdaysManagerBundle:YdaysManager:listeEtudiant

projet_ydays_manager_liste_objectif:
    path:     /listeObjectif
    defaults:
        _controller: ProjetYdaysManagerBundle:YdaysManager:listeObjectif

projet_ydays_manager_list_Entreprise:
    path:     /listEntreprises
    defaults:
        _controller: ProjetYdaysManagerBundle:Entreprise:listEntreprises

projet_ydays_manager_display_cr:
    path:     ficheProjet/allReports/{id}
    defaults:
        _controller: ProjetYdaysManagerBundle:Report:displayReport
    requirements:
       id: \d+

projet_ydays_manager_display_one_cr:
    path:     ficheProjet/allReports/report/{idReport}
    defaults:
        _controller: ProjetYdaysManagerBundle:Report:displayOneReport
    requirements:
       idReport: \d+

projet_ydays_manager_create_one_cr:
    path:     ficheProjet/allReports/newReport/{idProject}
    defaults:
        _controller: ProjetYdaysManagerBundle:Report:CreateOneReport
    requirements:
       idReport: \d+

projet_ydays_manager_accueil:
    path:     /accueil
    defaults:
        _controller: ProjetYdaysManagerBundle:YdaysManager:accueil

projet_ydays_manager_admin_demande:
    path:     /adminDemande
    defaults:
        _controller: ProjetYdaysManagerBundle:Desire:adminDemande


projet_ydays_manager_test_login:
    path:     /testLogin
    defaults:
        _controller: ProjetYdaysManagerBundle:YdaysManager:testLogin







#projet_ydays_manager_login:
#    path:     /login
#    defaults:
#        _controller: ProjetYdaysManagerBundle:YdaysManager:login